export declare class J360App {
    private jpegWorker;
    private capturer360;
    private webmRecorder;
    private ffmpegEncoder;
    private scene;
    private camera;
    private renderer;
    private canvas;
    private controls;
    private equiManaged;
    private meshes;
    private stereo;
    private vrSession;
    constructor();
    private startCapture360;
    private stopCapture360;
    private startWebMRecording: (fps?: number, includeAudio?: boolean) => void;
    private stopWebMRecording: () => Promise<void>;
    private stopWebMRecordingForCli: () => Promise<ArrayBuffer | null>;
    private startWasmRecording: (fps?: number) => Promise<void>;
    private stopWasmRecordingForCli: () => Promise<ArrayBuffer | null>;
    private toggleStereo;
    private enterVR;
    private captureFrameAsync;
    private init;
    private placeObjectsAroundYou;
    private locationNames;
    private makeSingleObject;
    private animate;
    private onWindowResize;
    bindWindow(): void;
}
export declare const j360App: J360App;
