export declare class J360App {
    private jpegWorker;
    private capturer360;
    private webmRecorder;
    private webCodecsRecorder;
    private ffmpegEncoder;
    private scene;
    private camera;
    private renderer;
    private canvas;
    private controls;
    private equiManaged;
    private meshes;
    private stereo;
    private recording;
    private vrSession;
    private vrHud;
    private hlsUrl;
    private rtmpUrl;
    constructor();
    private startCapture360;
    private stopCapture360;
    private startWebMRecording;
    private startWebCodecsRecording;
    private stopWebMRecording;
    private stopWebMRecordingForCli;
    private stopWebCodecsRecording;
    private stopWebCodecsRecordingForCli;
    private startWasmRecording;
    private stopWasmRecordingForCli;
    private startStreaming;
    private stopStreaming;
    private toggleStereo;
    private updateVrHud;
    private onVrSelect;
    private onVrSqueeze;
    private enterVR;
    private captureFrameAsync;
    private captureFrameAsyncForCli;
    addFrameProcessor(p: (frame: Uint8Array) => Uint8Array | Promise<Uint8Array>): void;
    private init;
    private placeObjectsAroundYou;
    private locationNames;
    private makeSingleObject;
    private animate;
    private onWindowResize;
    private startHLS;
    private stopHLS;
    private startRTMP;
    private stopRTMP;
    bindWindow(): void;
}
export declare const j360App: J360App;
